# Generated by Django 3.1.7 on 2021-03-24 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('FatherName', models.CharField(max_length=250)),
                ('MotherName', models.CharField(max_length=250)),
                ('PhoneNumber', models.CharField(max_length=10, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('District', models.CharField(max_length=250)),
                ('State', models.CharField(max_length=250)),
                ('moneyAvailable', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
